// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'dart:io';

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkDZSoYgG-D1YwSEjQZkYOjwSgqRhe8nU',
    appId: '1:689890085964:web:ac457db0e587e57addf8e9',
    messagingSenderId: '689890085964',
    projectId: 'time-pulse-dff6d',
    authDomain: 'time-pulse-dff6d.firebaseapp.com',
    storageBucket: 'time-pulse-dff6d.firebasestorage.app',
    measurementId: 'G-VNMPJK750H',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: Platform.environment['FIREBASE_OPTIONS_ANDROID_API_KEY']!,
    appId: Platform.environment['FIREBASE_OPTIONS_ANDROID_APP_ID']!,
    messagingSenderId: '689890085964',
    projectId: 'time-pulse-dff6d',
    storageBucket: 'time-pulse-dff6d.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: Platform.environment['FIREBASE_OPTIONS_IOS_API_KEY']!,
    appId: Platform.environment['FIREBASE_OPTIONS_IOS_APP_ID']!,
    messagingSenderId: '689890085964',
    projectId: 'time-pulse-dff6d',
    storageBucket: 'time-pulse-dff6d.firebasestorage.app',
    iosBundleId: 'com.example.timePulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBifT8LCD99yPUMLKw7BqibalW9DgKV4U0',
    appId: '1:689890085964:ios:bbd8aaa6685ab30fddf8e9',
    messagingSenderId: '689890085964',
    projectId: 'time-pulse-dff6d',
    storageBucket: 'time-pulse-dff6d.firebasestorage.app',
    iosBundleId: 'com.example.timePulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkDZSoYgG-D1YwSEjQZkYOjwSgqRhe8nU',
    appId: '1:689890085964:web:b6e270973afa418eddf8e9',
    messagingSenderId: '689890085964',
    projectId: 'time-pulse-dff6d',
    authDomain: 'time-pulse-dff6d.firebaseapp.com',
    storageBucket: 'time-pulse-dff6d.firebasestorage.app',
    measurementId: 'G-VX38F4JD2Y',
  );
}
